### ISSUE TITLE
How do I make an example work?

### ISSUE THREAD

**Issue by Jeff17Robbins** [vincentsarago/lambda-proxy#31]
https://github.com/vincentsarago/lambda-proxy gives as an example:

```
from lambda_proxy.proxy import API

APP = API(name="app")

@APP.route('/test/tests/<id>', methods=['GET'], cors=True)
def print_id(id):
    return ('OK', 'plain/text', id)
```

But, when I try to configure this on AWS with API Gateway and Lambda, I get this error:

```
{
  "errorMessage": "No view function for: /test/tests"
}
```

**Comment by vincentsarago** [comment]
Hi @Jeff17Robbins 

So you mean when you try to call `{api gateway url + stage}/test/tests/1` it doesn't work ?

**Comment by Jeff17Robbins** [comment]
Correct. I assume I don't know how to configure AWS API Gateway correctly and would love a simple set of instructions use the AWS Lambda and API Gateway consoles as to how to setup the `test/tests` example.

**Comment by vincentsarago** [comment]
and does `{api gateway url + stage}/docs` works ?

**Comment by Jeff17Robbins** [comment]
No.  I see this in my browser

**Comment by Jeff17Robbins** [comment]
Is this how to setup the lambda in the AWS console?

![image](https://user-images.githubusercontent.com/2102919/76177342-4b019f00-618a-11ea-84b1-5a775af7de4d.png)

**Comment by vincentsarago** [comment]
Yes that's correct, 
For API gateway configuration just make sure to set `{proxy+}` for the path. 

I usually use serverless for deployement, like in https://github.com/developmentseed/cogeo-tiler/blob/master/serverless.yml

**Comment by Jeff17Robbins** [comment]
I also was unsure about how to setup AWS API Gateway

![image](https://user-images.githubusercontent.com/2102919/76177474-bba8bb80-618a-11ea-9de1-035c22682e72.png)

Do I setup a "proxy" resource?

![image](https://user-images.githubusercontent.com/2102919/76177542-f874b280-618a-11ea-9287-9ffb1dc0f7df.png)

**Comment by vincentsarago** [comment]
oh I this this has to do with the new API Type REST integration which is not yet supported by this library. can you try with API Type HTTP

**Comment by Jeff17Robbins** [comment]
Ah, I had no idea.  Sorry!!

Ok, I tried that and when I access

`XXXXXXXXXXX.execute-api.us-east-1.amazonaws.com/docs`

I see 

![image](https://user-images.githubusercontent.com/2102919/76178065-8d2be000-618c-11ea-9feb-30a3d02adff4.png)

**Comment by kylebarron** [comment]
> oh I this this has to do with the new API Type REST integration which is not yet supported by this library. can you try with API Type HTTP

The reverse. Type HTTP isn't supported; REST is. Failed to load API definition is what I got when I tried to set it up with HTTP

**Comment by Jeff17Robbins** [comment]
Thanks @kylebarron .  I went back to the REST API.  Apparently one has to set up TWO resources, root, and `{proxy+}`.  Once I did that, a simple test Lambda worked!

![image](https://user-images.githubusercontent.com/2102919/76210840-5204cd80-61db-11ea-81dc-150949355f45.png)


```
from lambda_proxy.proxy import API

APP = API(name="app")

@APP.route('/', methods=['GET'], cors=True)
def print_id(id=None):
    return ('OK', 'application/json', f'hello {id}')
```

tested with this test event
```
{
  "httpMethod": "GET",
  "path": "/",
  "queryStringParameters": {
    "id": "Fred"
  }
}
```

![image](https://user-images.githubusercontent.com/2102919/76210999-a7d97580-61db-11ea-815a-8db7185af11d.png)

**works!**



But...


If I add `<id>` to my `@APP.route()` code

```
from lambda_proxy.proxy import API

APP = API(name="app")

@APP.route('/<id>', methods=['GET'], cors=True)
def print_id(id=None):
    return ('OK', 'application/json', f'hello {id}')
```

the test fails with

```
Response:
{
  "statusCode": 400,
  "headers": {
    "Content-Type": "application/json"
  },
  "body": "{\"errorMessage\": \"No view function for: /\"}"
}
```

**Comment by vincentsarago** [comment]
@Jeff17Robbins sorry about that, setting API Gateway from lambda console is a pain, 

here 


Here is the SAM template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  testproxy:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.app
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::524387336408:role/service-role/test-proxy-role-b7aho2ym'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
      Layers:
        - 'arn:aws:lambda:us-east-1:524387336408:layer:gdal30-py37-cogeo:8'
```

with this code

```python
"""Test."""

from lambda_proxy.proxy import API

app = API(name="app")


@app.route('/test/<id>', methods=['GET'], cors=True)
def print_id(id):
    return ('OK', 'application/json', f"test - {id}")


@app.route('/<id>', methods=['GET'], cors=True)
def print_id(id):
    return ('OK', 'application/json', id)
```

Note: because I'm using a lambda layer I working in python3.7
