### ISSUE TITLE
Http API

### ISSUE THREAD

**Issue by kylebarron** [vincentsarago/lambda-proxy#39]
From https://github.com/developmentseed/cogeo-mosaic-tiler/issues/1

It would be nice to optionally support HTTP APIs in `lambda-proxy` in addition to the existing REST API. HTTP APIs are cheaper at $1/1M instead of $3.50/1M, and often a there's no need to use a REST API. ([List of differences here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html)).

For a simple `serverless.yml`, you can just change

```yml
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
```
to
```yml
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'
          cors: true
```

Most endpoints work fine, but I think endpoints that rely on relative URLs don't, i.e. `/docs`:
![image](https://user-images.githubusercontent.com/15164633/78200402-cf72d500-744b-11ea-8b95-427ac55654ed.png)

I'm gonna try to dig into this more
